### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [jaygala223/DSA-practice#1]
Hey,
I am a beginner here who would definitely use these resources.
I would like to be assigned to improve the README.md for practice

Also, I wanted some tips/suggestions about GSoD.

Sorry to raise an impromptu issue, excuse my excitement.

Regards,
Atharva

**Comment by jaygala223** [comment]
Hi Atharva,

Please go ahead and make changes to the README.md for practice.

For anything else you can email me or connect with me on Linkedin. I will be more than happy to help you out.

Good luck!

**Comment by the-amazing-atharva** [comment]
Hey,
I wanted to ask how to get selected for season of docs as a beginner - (I am learning CSS and web dev right now, with knowledge of C/C++ and I write regular blogs on Hashnode and Medium). 
What do you suggest I do?
